% RUN_LPS_MP  Thin driver for lps_sim_csr_mp.m
%
%   Pipeline: particles -> Linac 1 -> Arc 1 (CSR) -> Linac 2 -> Arc 2 (CSR).

clear; clc; close all;

% =================== USER INPUTS ===================
bunchfile = 'beam_merger.ast';     % ASTRA-style particle file
Q_total   = 50e-12;                % [C]

% --- Linac parameters ---
E_ref0 = 11;                       % [MeV]
A      = 500;                      % [MeV]
phi1   = 6.92;                      % [deg]
phi2   = 6.92;                      % [deg]
f      = 1.3e9;                    % [Hz]

% --- Arc 1 ---
T566_1        = -9;                % [m]
r56_arc1_file = 'r56';
rho_list_arc1 = [  1.9319;  -1.9319; ...
                   1.3066;   1.3066;   1.3066;   1.3066; ...
                   4.3007;  -2.1503;   4.3007; ...
                   1.3066;   1.3066;   1.3066;   1.3066; ...
                  -1.9319;   1.9319 ];

% --- Arc 2 ---
T566_2        = -3.25;              % [m]
r56_arc2_file = 'r56.line_dat';
rho_list_arc2 = [ 4.3*ones(1,4),  2.79*ones(1,4),  -3.8,  3.8 ];

% --- CSR settings ---
n_grid     = 200;
smooth_win =50;

% sigma_zf overrides (auto-derived if empty)
sigzf_arc1 = [];
sigzf_arc2 = 12e-6;

% Arc-2 Lorentz factor override (empty => derive from E_ref2)
gamma_rel = 1000 / 0.511;

% Bend-count restrictions (0 = use all detected)
n_bends_arc1 = 0;
n_bends_arc2 = 0;

% dR56 transport-only overrides
dR56_1 = 0;
dR56_2 = 0;

% R56 line file columns (same for both arcs here)
s_col   = 2;
R56_col = 3;

% Linac-2 active cavity length [m] (sum of accelerating cavities)
% 0 = thin-cavity (drops T-elements and within-cavity R56)
L_cav_2 = 40;
% ===================================================

p = struct( ...
    'bunchfile',      bunchfile, ...
    'Q_total',        Q_total, ...
    'E_ref0',         E_ref0, ...
    'A',              A, ...
    'phi1',           phi1, ...
    'phi2',           phi2, ...
    'f',              f, ...
    'T566_1',         T566_1, ...
    'r56_arc1_file',  r56_arc1_file, ...
    'rho_list_arc1',  rho_list_arc1, ...
    'T566_2',         T566_2, ...
    'r56_arc2_file',  r56_arc2_file, ...
    'rho_list_arc2',  rho_list_arc2, ...
    'n_grid',         n_grid, ...
    'smooth_win',     smooth_win, ...
    'sigzf_arc1',     sigzf_arc1, ...
    'sigzf_arc2',     sigzf_arc2, ...
    'gamma_rel',      gamma_rel, ...
    'n_bends_arc1',   n_bends_arc1, ...
    'n_bends_arc2',   n_bends_arc2, ...
    'dR56_1',         dR56_1, ...
    'dR56_2',         dR56_2, ...
    's_col',          s_col, ...
    'R56_col',        R56_col, ...
    'L_cav_2',        L_cav_2, ...
    'plot',           1, ...
    'verbose',        1 );

% --- Run pipeline ---------------------------------------------------------
out = lps_sim_csr_mp(p);

if ~out.is_valid
    return;
end
